@echo off
echo Starting STAR Video Processing Servers...

echo Starting Backend Server...
start cmd /k "cd webapp\backend && start_backend.bat"

echo Starting Frontend Server...
start cmd /k "cd webapp\frontend-next && .\start_frontend.bat"

echo Both servers are starting...
echo Backend will be available at: http://localhost:8000
echo Frontend will be available at: http://localhost:3000 